### ISSUE TITLE
Feedback for Sharktopoda 2 specs

### ISSUE THREAD

**Issue by hohonuuli** [mbari-org/Sharktopoda1#2]
This is for the new specs for mbari-org/vars-feedback#4

**Comment by hohonuuli** [comment]
From @kevinsbarnard 

```
"open", existing UUID:
    Ambiguity:
        Case 1: opened new window
        Case 2: showed existing one
    "status": "ok" -> "status": "shown" for case 2?
"close", no matching UUID:
    Ambiguity:
        Case 1: closed existing window
        Case 2: didn't close anything
    "status": "ok" -> "status": "failed" for case 2?
"request information" vs. "request all information":
    "request information" responds with 4 fields: uuid, url, durationMillis, frameRate
    "request all information" responds with 3 fields (for each open window): uuid, url, durationMillis
    Why no frameRate in latter?
    Why is frameRate a string?
"play":
    Why is rate a string?
    How can we get current playback rate? Maybe include in the "request status" response?
"request elapsed time" / "seek elapsed time" / "frame capture":
    Why is elapsedTimeMillis a string?
"request status":
    Replace classifications of playback rate with actual playback rate?
"frame advance":
    Only forward
    Specify direction or add separate "frame regress"?
"add localizations":
    Add optional field for durationMillis? Can set this via "update localizations" but would be laborious to send two commands for each set
    What is default durationMillis?
```

**Comment by hohonuuli** [comment]
re: "play" /"request elapsed time" / "seek elapsed time" / "frame capture" fields that should be numbers. Fixed in spec. They were correct in test implementation.

**Comment by hohonuuli** [comment]
re: "open" / "close" ambiguities. Leaving as is as no other remote action would need to be taken for the "failed" cases. i.e. the video is already open/closed.

**Comment by hohonuuli** [comment]
re: "request information" vs. "request all information": whoops. Fixed now. Both commands will return elapsedTimeMillis and frameRate

**Comment by hohonuuli** [comment]
re "add localizations". Added durationMillis to both add and update. Added color to update.

**Comment by hohonuuli** [comment]
Remaining todos:

- [ ] Add `rate` (actual playback rate) to `request status` response. 
- [ ] Add direction flag to frame advance or add frame regress.

**Comment by kevinsbarnard** [comment]
Some more feedback, re: UI spec

---
- Open/Open URL
  - Any limitation on file type?
  - Add "pause the video once opened"
- "UPD" -> "UDP" in a few places
- Preferences
  - Annotations
    - Add hotkey to toggle "Show Annotations"?
    - Time Window
      - How does this resolve with the individual localization `duration`?
        - Add setting to disable global time window? Or maybe a toggle between "global" and "per-localization"
          - Global time window makes sense for still-frame localizations, but doesn't make sense for track localizations
          - Applications like BoxJelly would prefer to show localizations by their time/duration fields, i.e. in the interval [`elapsedTimeMillis`, `elapsedTimeMillis` + `duration`]
  - Where does the localization editing "The user hits enter or other definable key if enter can't be used. If we can't use enter, allows the key to be set in preferences." setting live?
- Selecting a localization
  - What does a selected localization look like?
  - Is the valid click region limited to the border pixels themselves? I.e. by decreasing the border width, will that make it harder to select a localization?

- Editing a localization:
  - What do the move/resize controls look like?
  - When are the controls shown? I would suggest on-hover
  - Is an update command sent if the localization is unmodified?

- Creating a localization:
  - "It should then immediately select the localization and send a select message to the remote app.": Does the select command only contain the new localization, or does it include any other localizations previously selected?

**Comment by hohonuuli** [comment]
@kevinsbarnard Thank you!

**Comment by hohonuuli** [comment]
Comments have been integrated into the spec.
